[project]
name = "nls-controlhub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "richcolorlog>=1.44.17",
    "toml>=0.10.2",
]
